// Экшены для загрузки фото
export const LOAD_PHOTOS_LOADING = "LOAD_PHOTOS_LOADING";
export const LOAD_PHOTOS_ERROR = "LOAD_PHOTOS_ERROR";
export const LOAD_PHOTOS_SUCCESS = "LOAD_PHOTOS_SUCCESS";

// Экшены для загрузки одного фото
export const LOAD_SINGLE_PHOTO_LOADING = "LOAD_SINGLE_PHOTO_LOADING";
export const LOAD_SINGLE_PHOTO_ERROR = "LOAD_SINGLE_PHOTO_ERROR";
export const LOAD_SINGLE_PHOTO_SUCCESS = "LOAD_SINGLE_PHOTO_SUCCESS";
